// SPDX-License-Identifier: GPL-3.0-or-later
//
// M6.1: the turn and timeline axes are ordinary lattice axes.
//
// This is the payoff the architecture was built for (ADR-0007): a time jump is a
// direction with a nonzero turn component, generated by the same atom expansion as a
// rook's file move. Nothing in movegen, geometry or the position hash knows that "turn"
// means anything in particular - which is exactly what makes faithful 5D chess a matter
// of policy on top, not a second engine.
#include <catch2/catch_test_macros.hpp>

#include "game/game.hpp"
#include "movegen/movegen.hpp"
#include "oracle/oracle.hpp"
#include "variant/standard.hpp"

using namespace cb;

namespace {

/// Standard chess pieces on a board with two extra axes: three turns and two timelines.
///
/// Only the two kings are placed, on the first board, so the perft stays small; the
/// point is the shape of the lattice, not the size of the position.
VariantSpec temporalSandbox() {
  const auto base = makeStandardChess();
  REQUIRE(base.has_value());

  VariantSpec v;
  v.name = "temporal-sandbox";
  const std::vector<AxisDecl> axes{
      {8, AxisKind::Spatial, "file"},
      {8, AxisKind::Spatial, "rank"},
      {3, AxisKind::Temporal, "turn"},
      {2, AxisKind::Multiverse, "line"},
  };
  v.dims = DimSpec::create(axes).value();
  v.geom = Geometry::create(v.dims, {}).value();
  v.orientationAxis = 1;
  v.pieces = base->pieces;  // atoms are dimension-agnostic; finalize re-expands them

  const auto place = [&](int file, int rank, const char* name, Color color) {
    Coord c(v.dims.dims());
    c.c[0] = static_cast<std::int16_t>(file);
    c.c[1] = static_cast<std::int16_t>(rank);
    c.c[2] = 0;  // turn
    c.c[3] = 0;  // line
    v.start.push_back(StartPiece{c, v.findPiece(name), color});
  };
  place(4, 0, "king", Color::White);
  place(4, 7, "king", Color::Black);
  // findPiece needs the piece list, which is copied above.
  REQUIRE(v.finalize().has_value());
  return v;
}

}  // namespace

TEST_CASE("turn and timeline are declared axis kinds, not special cases",
          "[unit][temporal]") {
  const VariantSpec v = temporalSandbox();
  REQUIRE(v.dims.dims() == 4);
  CHECK(v.dims.kind(0) == AxisKind::Spatial);
  CHECK(v.dims.kind(1) == AxisKind::Spatial);
  CHECK(v.dims.kind(2) == AxisKind::Temporal);
  CHECK(v.dims.kind(3) == AxisKind::Multiverse);
  CHECK(v.dims.cellCount() == 8u * 8u * 3u * 2u);
}

TEST_CASE("a rook's atoms expand across the temporal axes too", "[unit][temporal]") {
  const VariantSpec v = temporalSandbox();
  const PieceTypeId rook = v.findPiece("rook");
  bool jumpsInTurn = false;
  bool jumpsInLine = false;
  for (const MoveAtom& atom : v.pieces[rook].atoms) {
    for (std::uint32_t di = atom.dirBegin[0]; di < atom.dirEnd[0]; ++di) {
      const Direction& d = v.dirTable[di];
      if (d.v[2] != 0) jumpsInTurn = true;
      if (d.v[3] != 0) jumpsInLine = true;
    }
  }
  CHECK(jumpsInTurn);
  CHECK(jumpsInLine);
}

TEST_CASE("a time jump is an ordinary legal move", "[unit][temporal]") {
  const VariantSpec v = temporalSandbox();
  Game g(v);
  const Move* jump = nullptr;
  for (const Move& m : g.legalMoves()) {
    const Coord from = v.dims.toCoord(m.from);
    const Coord to = v.dims.toCoord(m.to);
    if (to.c[2] != from.c[2] || to.c[3] != from.c[3]) {
      jump = &m;
      break;
    }
  }
  REQUIRE(jump != nullptr);
  const Move chosen = *jump;  // legalMoves() is invalidated by play
  const Coord to = v.dims.toCoord(chosen.to);
  REQUIRE(g.play(chosen).has_value());
  REQUIRE_FALSE(g.position().at(chosen.to).empty());
  CHECK((to.c[2] != 0 || to.c[3] != 0));  // the piece left the first board
}

TEST_CASE("movegen and the oracle still agree with temporal axes present",
          "[unit][temporal]") {
  const VariantSpec v = temporalSandbox();
  Position p = Position::startPosition(v);
  Position q = Position::startPosition(v);
  const MoveGen gen(v);
  REQUIRE(gen.perft(p, 1) > 0);
  REQUIRE(gen.perft(p, 2) == oracle::perft(q, 2));
}
