// SPDX-License-Identifier: GPL-3.0-or-later
// The standard perft suite. These node counts are external ground truth, widely
// replicated; they are transcribed here, never generated by this engine.
//
// Their value is that they exercise exactly the rules that a generalized engine is
// most likely to get subtly wrong: Kiwipete is dense with castling and pins,
// position 3 is an en-passant and promotion minefield, position 4 has promotions
// with check, and position 5 is a known castling-rights-bug catcher.
//
// NOTE: the suite's usual sixth position is deliberately absent. The FEN/count
// pair available to the author here was internally inconsistent - a hand count of
// the position gives 42 legal moves where the transcribed golden says 46 - and an
// unverifiable golden is worse than no golden, because the first thing it does on
// failure is send someone hunting a bug that is not there. It should be restored
// from a primary source, with the count checked against this engine only after the
// FEN is confirmed independently.
#include <catch2/catch_test_macros.hpp>

#include "io/fen.hpp"
#include "movegen/movegen.hpp"
#include "variant/standard.hpp"

using namespace cb;

namespace {

struct PerftCase {
  const char* name;
  const char* fen;
  std::uint64_t nodes[7];  // index = depth; 0 means "not covered"
};

// clang-format off
const PerftCase kCases[] = {
    {"initial", "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
     {1, 20, 400, 8902, 197281, 4865609, 119060324}},
    {"kiwipete", "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1",
     {1, 48, 2039, 97862, 4085603, 193690690, 0}},
    {"position3", "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1",
     {1, 14, 191, 2812, 43238, 674624, 11030083}},
    {"position4", "r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1",
     {1, 6, 264, 9467, 422333, 15833292, 0}},
    {"position5", "rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8",
     {1, 44, 1486, 62379, 2103487, 89941194, 0}},
};
// clang-format on

void runToDepth(const PerftCase& c, int maxDepth) {
  const auto v = makeStandardChess();
  REQUIRE(v.has_value());
  auto p = fromFen(*v, c.fen);
  REQUIRE(p.has_value());
  const MoveGen gen(*v);
  for (int d = 1; d <= maxDepth; ++d) {
    if (c.nodes[d] == 0) continue;
    CAPTURE(c.name, c.fen, d);
    REQUIRE(gen.perft(*p, d) == c.nodes[d]);
  }
}

}  // namespace

TEST_CASE("perft suite to depth 4", "[perft]") {
  for (const PerftCase& c : kCases) runToDepth(c, 4);
}

TEST_CASE("perft suite to depth 5", "[perft][slow]") {
  for (const PerftCase& c : kCases) runToDepth(c, 5);
}

TEST_CASE("perft suite to depth 6", "[perft-deep][.]") {
  // Tagged outside [perft] on purpose: Catch2 runs a hidden test when a filter
  // matches any of its tags, so sharing [perft] would silently pull 119M nodes
  // into the fast suite.
  // Excluded from the default run by the '.' tag; the nightly job asks for it
  // explicitly. Depth 6 on the initial position is 119,060,324 nodes.
  for (const PerftCase& c : kCases) runToDepth(c, 6);
}

TEST_CASE("perftDivide sums to perft", "[perft]") {
  // The bisection tool has to be trustworthy: it is what localises a node-count
  // mismatch to a single move (the cb-perft-golden skill).
  const auto v = makeStandardChess();
  auto p = fromFen(*v, kCases[1].fen);
  const MoveGen gen(*v);
  const auto divided = gen.perftDivide(*p, 3);
  std::uint64_t total = 0;
  for (const auto& e : divided) total += e.nodes;
  REQUIRE(divided.size() == 48);
  REQUIRE(total == gen.perft(*p, 3));
}
