# SPDX-License-Identifier: GPL-3.0-or-later
#
# Turn compiled SPIR-V files into a header of byte arrays, so shaders ship inside the
# binary instead of as files that could go missing or fall out of step with the code.
file(WRITE ${OUT} "// SPDX-License-Identifier: GPL-3.0-or-later\n")
file(APPEND ${OUT} "// Generated by cmake/EmbedSpirv.cmake - do not edit.\n#pragma once\n\n")
file(APPEND ${OUT} "#include <cstdint>\n#include <span>\n\nnamespace cb::render::spv {\n\n")
foreach(spv IN LISTS SPVS)
  get_filename_component(name ${spv} NAME)
  string(REPLACE "." "_" symbol ${name})
  file(READ ${spv} data HEX)
  string(REGEX MATCHALL "([0-9a-f][0-9a-f])" bytes ${data})
  list(JOIN bytes ",0x" joined)
  file(APPEND ${OUT} "inline constexpr std::uint8_t ${symbol}[] = {0x${joined}};\n")
  file(APPEND ${OUT} "inline std::span<const std::uint8_t> ${symbol}_span() { return ${symbol}; }\n\n")
endforeach()
file(APPEND ${OUT} "}  // namespace cb::render::spv\n")
